[destination.s3.credentials]
# These will be loaded from environment variables in production
aws_access_key_id = "${AWS_ACCESS_KEY_ID}"
aws_secret_access_key = "${AWS_SECRET_ACCESS_KEY}"
region_name = "${AWS_DEFAULT_REGION}"