name: 'Initialize CDK environment'
description: 'Sets up Node.js, installs dependencies, and configures AWS credentials'

inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
  node-version:
    description: 'Node.js version'
    required: false
    default: '20'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      shell: bash

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: cd infrastructure && npm ci
      shell: bash