[sources.oyez_scotus_source]
# API rate limiting configuration
api_rate_limit = 1  # 1 request per second to respect Oyez API

[destination.s3]
# S3 configuration
bucket_name = "scotustician"
region_name = "us-east-1"

# Use existing S3 path structure: raw/oa/
layout = "raw/oa/{table_name}_{load_id}.{file_id}.{ext}"

[pipeline]
# Pipeline configuration
dataset_name = "scotustician_raw"