name: Deploy ETL Service

on:
  push:
    paths:
      - 'etl/**'
      - 'infra/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install CDK dependencies
        run: |
          cd infra
          npm install

      - name: Deploy ETL CDK Stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          cd infra
          npm run build
          npx cdk deploy ScotusticianEtlStack --require-approval never
